import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'Kinyarwanda' | 'French' | 'English' | 'Swahili' | 'Portuguese' | 'Spanish' | 'Russian';

export interface Mood {
  label: string;
  emoji: string;
  color: string;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  selectedMood: Mood | null;
  setMood: (mood: Mood) => void;
  userName: string;
  setUserName: (name: string) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  English: {
    home: "Home", play: "Play", circles: "Circles", library: "Library", settings: "Settings", journey: "Journey", explore: "Explore",
    welcome: "Welcome back", activities: "Activities", current_mood: "Current Mood", mark_complete: "Mark as Complete",
    daily_reflection: "Daily Reflection", mindful_moment: "Mindful Moment", playlist: "Today's Playlist",
    search_youtube: "Listen on YouTube", select_language: "Select Language", continue: "Continue",
    understand_begin: "Understand & Begin", last_7_days: "Last 7 Days", welcome_to: "Welcome to", how_feeling: "How are you feeling right now?",
    before_begin: "Before We Begin", our_commitment: "Our Commitment", 
    commitment_text: "Lumora provides a safe mental wellness space. We listen and guide, but we are not a replacement for professional clinical therapy.", 
    sys_perms: "System Permissions", camera: "Camera", camera_desc: "PROFILE & WORKSHOP UPLOADS",
    notifications: "Notifications", notify_desc: "REMINDERS & GUARDIAN ALERTS",
    location: "Location", loc_desc: "SUGGESTED NEARBY ACTIVITIES",
    Radiant: "Radiant", Peaceful: "Peaceful", Tired: "Tired", Anxious: "Anxious", Sad: "Sad", Reflective: "Reflective",
    top_pick: "Top Pick", duration: "Duration", intensity: "Intensity",
    preparing: "Preparing your calm space", select_energy: "Select your current energy", skip: "Skip this step",
    welcome_plain: "welcome", sign_in: "Sign In", sign_up: "Sign Up", 
    user_placeholder: "Choose a professional username", email_placeholder: "Email address", pass_placeholder: "Secure password",
    forgot_pass: "Forgot Password?", begin: "Let's Begin", ethics_guide: "By joining, you agree to our professional ethics and mindfulness guidelines.",
    sanctuary: "Your Mindful Sanctuary",
    settings_desc: "Customize your gentle space", account: "Account", profile: "Profile Information", 
    lang_theme: "Language & Theme", app_lang: "App Language", dark_mode: "Dark Mode",
    safety_privacy: "Safety & Privacy", trusted_guardian: "Trusted Guardian", active_protection: "Active Protection",
    privacy_controls: "Privacy Controls", support_lumora: "Support Lumora", log_out: "Log Out",
    circles_desc: "A Safe Space for Sharing", share_exp: "Share your experience", sharing_anon: "Sharing as Anonymous...",
    sharing_as: "Sharing as", post_anon: "Post Anonymously", post_as_user: "Post as", share_now: "Share Now", reply: "Reply",
    group_1: "Anxiety Support", group_2: "PTSD Warriors", group_3: "Depression Recovery", group_4: "Mindfulness Circle", group_5: "Grief & Loss", group_6: "Teen Mental Health",
    act_1_title: "Box Breathing", act_1_desc: "A powerful naval SEAL technique to regulate your autonomic nervous system.",
    act_2_title: "Nature Immersion", act_2_desc: "Scientifically proven to reduce cortisol levels and blood pressure.",
    act_3_title: "Body Scan Meditation", act_3_desc: "Deeply connect with physical sensations to ground your mind.",
    act_4_title: "Gratitude Journaling", act_4_desc: "Rewire your brain for positivity by identifying positive outcomes.",
    book_1_title: "Man's Search for Meaning", book_1_auth: "Viktor Frankl", book_1_desc: "Viktor Frankl's timeless masterpiece on how to find purpose in suffering.",
    book_2_title: "The Body Keeps the Score", book_2_auth: "Bessel van der Kolk", book_2_desc: "Explores the deep neurological impact of trauma.",
    Meditations: "Meditations",
    quote_1: "The soul becomes dyed with the color of its thoughts.",
    quote_2: "Peace comes from within. Do not seek it without.",
    quote_3: "The present moment is filled with joy and happiness.",
    quote_4: "Quiet the mind, and the soul will speak.",
    quote_5: "Nature does not hurry, yet everything is accomplished.",
    reflection_title: "Evening Calm", reflection_text: "Identify one thing today that brought you a sense of quiet peace.",
    playlist_desc: "Curated Soundscapes", min_suffix: "min", 
    Medium: "Medium", High: "High", Low: "Low",
    emotional_resonance: "Emotional Resonance", current_peak: "Current Peak", status: "Status", rank: "Rank", days: "Days", balance: "Balance", member: "Member",
    rising: "Rising", falling: "Falling", stable: "Stable",
    setting_2fa: "Two-Factor Auth", setting_2fa_desc: "Enhanced Security", 
    community_other: "Community & Other",
    MON: "MON", TUE: "TUE", WED: "WED", THU: "THU", FRI: "FRI", SAT: "SAT", SUN: "SUN",
    post_1_text: "Today I managed to leave the house for the first time in two weeks.",
    post_2_text: "I had my first panic-free day in months.",
    post_3_text: "Grief doesn't get smaller. You just grow bigger around it.",
    access_resource: "Access Resource", read_now: "Read Now",
    personal_growth: "Personal Growth Analytics", mindful_streak: "Mindful Streak", calm_walker: "Calm Walker",
    recent_milestones: "Recent Milestones", peace_guardian: "7 Day Peace Guardian", peace_guardian_desc: "Maintained a stable mood for a full week.",
    clarity_spark: "Spark of Clarity", clarity_spark_desc: "Completed 5 meditations in a single day.",
    daily_insight: "Your energy is flowing beautifully today.", rank: "Rank", days: "Days", balance: "Balance",
    guardian_title: "Trusted Guardian", guardian_subtitle: "Safety & Support Network",
    guardian_desc: "Add someone you trust who we can reach out to if you need extra support.",
    guardian_name_placeholder: "Guardian's Name", guardian_email_placeholder: "Guardian's Email",
    guardian_phone_placeholder: "Guardian's Phone Number", guardian_fill_fields: "Please fill in all guardian details",
    guardian_saved: "Guardian information securely saved", continue_journey: "Continue Journey", skip_for_now: "Skip for now",
    saving: "Saving...",
    quote_6: "Happiness is not something readymade. It comes from your own actions.",
    quote_7: "The only way to do great work is to love what you do.",
    quote_8: "Believe you can and you're halfway there.",
    quote_9: "Act as if what you do makes a difference. It does.",
    quote_10: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    quote_11: "Never bend your head. Always hold it high. Look the world straight in the eye.",
    quote_12: "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    quote_13: "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    quote_14: "Try to be a rainbow in someone else's cloud.",
    quote_15: "You do not find the happy life. You make it.",
    quote_16: "The most wasted of all days is one without laughter.",
    quote_17: "Stay close to anything that makes you glad you are alive.",
    quote_18: "Make each day your masterpiece.",
    quote_19: "Happiness often sneaks in through a door you didn't know you left open.",
    quote_20: "The power of imagination makes us infinite.",
  },
  French: {
    home: "Accueil", play: "Jouer", circles: "Cercles", library: "Bibliothèque", settings: "Paramètres", journey: "Parcours", explore: "Explorer",
    welcome: "Bon retour", activities: "Activités", current_mood: "Humeur", mark_complete: "Terminer",
    daily_reflection: "Réflexion", mindful_moment: "Moment conscient", playlist: "Playlist",
    search_youtube: "YouTube", select_language: "Choisir la Langue", continue: "Continuer",
    understand_begin: "Comprendre & Commencer", last_7_days: "7 jours", welcome_to: "Bienvenue à", how_feeling: "Comment ça va ?",
    before_begin: "Avant de Commencer", our_commitment: "Notre Engagement",
    commitment_text: "Lumora offre un espace de bien-être sûr. Nous écoutons et guidons, mais ne remplaçons pas une thérapie clinique professionnelle.",
    sys_perms: "Autorisations Système", camera: "Caméra", camera_desc: "UPLOADS DE PROFIL",
    notifications: "Notifications", notify_desc: "RAPPELS ET ALERTES",
    location: "Localisation", loc_desc: "ACTIVITÉS À PROXIMITÉ",
    Radiant: "Rayonnant", Peaceful: "Paisible", Tired: "Fatigué", Anxious: "Anxieux", Sad: "Triste", Reflective: "Réfléchi",
    top_pick: "Choix", duration: "Durée", intensity: "Intensité",
    preparing: "Préparation de votre espace", select_energy: "Choisissez votre énergie", skip: "Passer cette étape",
    welcome_plain: "bienvenue", sign_in: "Se Connecter", sign_up: "S'inscrire",
    user_placeholder: "Nom d'utilisateur professionnel", email_placeholder: "Adresse e-mail", pass_placeholder: "Mot de passe sécurisé",
    forgot_pass: "Mot de passe oublié ?", begin: "Commençons", ethics_guide: "En rejoignant, vous acceptez notre éthique professionnelle.",
    sanctuary: "Votre Sanctuaire de Pleine Conscience",
    settings_desc: "Personnalisez votre espace", account: "Compte", profile: "Profil",
    lang_theme: "Langue & Thème", app_lang: "Langue de l'App", dark_mode: "Mode Sombre",
    safety_privacy: "Sécurité & Confidentialité", trusted_guardian: "Gardien de Confiance", active_protection: "Protection Active",
    privacy_controls: "Confidentialité", support_lumora: "Soutenir Lumora", log_out: "Déconnexion",
    circles_desc: "Espace d'échange sécurisé", share_exp: "Partagez votre expérience", sharing_anon: "En tant qu'anonyme...",
    sharing_as: "En tant que", post_anon: "Poster Anonymement", post_as_user: "Poster en tant que", share_now: "Partager", reply: "Répondre",
    group_1: "Soutien Anxiété", group_2: "Guerriers PTSD", group_3: "Récupération Dépression", group_4: "Cercle Conscient", group_5: "Deuil & Perte", group_6: "Santé Ados",
    act_1_title: "Respiration Carrée", act_1_desc: "Technique des SEALs pour réguler le système nerveux.",
    act_2_title: "Immersion Nature", act_2_desc: "Réduit scientifiquement le cortisol et la tension artérielle.",
    act_3_title: "Scan Corporel", act_3_desc: "Connectez-vous aux sensations physiques pour calmer l'esprit.",
    act_4_title: "Journal de Gratitude", act_4_desc: "Reprogrammez votre cerveau pour la positivité.",
    book_1_title: "Découvrir un sens à sa vie", book_1_desc: "L'œuvre de Viktor Frankl sur la recherche de sens.",
    book_2_title: "Le corps n'oublie rien", book_2_desc: "Explore l'impact neurologique des traumatismes.",
    quote_1: "L'âme se teint de la couleur de ses pensées.",
    quote_2: "La paix vient de l'intérieur. Ne la cherchez pas ailleurs.",
    quote_3: "Le moment présent est rempli de joie et de bonheur.",
    quote_4: "Calmez l'esprit, et l'âme parlera.",
    quote_5: "La nature ne se presse pas, pourtant tout est accompli.",
    reflection_title: "Calme du Soir", reflection_text: "Identifiez une chose aujourd'hui qui vous a apporté la paix.",
    playlist_desc: "Paysages Sonores", min_suffix: "min",
    Medium: "Moyen", High: "Élevé", Low: "Faible",
    emotional_resonance: "Résonance Émotionnelle", current_peak: "Pic Actuel", status: "Statut", rank: "Rang", days: "Jours", balance: "Équilibre", member: "Membre",
    rising: "En hausse", falling: "En baisse", stable: "Stable",
    setting_2fa: "Auth à Deux Facteurs", setting_2fa_desc: "Sécurité Renforcée",
    community_other: "Communauté & Autre",
    MON: "LUN", TUE: "MAR", WED: "MER", THU: "JEU", FRI: "VEN", SAT: "SAM", SUN: "DIM",
    post_1_text: "Aujourd'hui, j'ai réussi à sortir de la maison.",
    post_2_text: "J'ai eu ma première journée sans panique.",
    post_3_text: "Le deuil ne devient pas plus petit.",
    access_resource: "Accéder", read_now: "Lire",
    personal_growth: "Analyses de Croissance", mindful_streak: "Série de Pleine Conscience", calm_walker: "Marcheur Calme",
    recent_milestones: "Jalons Récents", peace_guardian: "Gardien de la Paix", peace_guardian_desc: "Humeur stable pendant une semaine.",
    clarity_spark: "Étincelle de Clarté", clarity_spark_desc: "5 méditations complétées en un jour.",
    daily_insight: "Votre énergie circule magnifiquement.", rank: "Rang", days: "Jours", balance: "Équilibre",
    guardian_title: "Gardien de Confiance", guardian_subtitle: "Réseau de Sécurité & Soutien",
    guardian_desc: "Ajoutez quelqu'un en qui vous avez confiance que nous pourrons contacter si vous avez besoin d'un soutien supplémentaire.",
    guardian_name_placeholder: "Nom du Gardien", guardian_email_placeholder: "E-mail du Gardien",
    guardian_phone_placeholder: "Numéro de Téléphone du Gardien", guardian_fill_fields: "Veuillez remplir tous les détails du gardien",
    guardian_saved: "Informations du gardien enregistrées en toute sécurité", continue_journey: "Continuer le Parcours", skip_for_now: "Passer pour l'instant",
    saving: "Enregistrement...",
    quote_6: "Le bonheur n'est pas quelque chose de déjà fait. Il vient de vos propres actions.",
    quote_7: "La seule façon de faire du bon travail est d'aimer ce que vous faites.",
    quote_8: "Croyez que vous pouvez et vous êtes à mi-chemin.",
    quote_9: "Agissez comme si ce que vous faites faisait une différence. C'est le cas.",
    quote_10: "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte.",
    quote_11: "Ne baissez jamais la tête. Gardez-la toujours haute. Regardez le monde droit dans les yeux.",
    quote_12: "Ce que vous obtenez en atteignant vos objectifs n'est pas aussi important que ce que vous devenez en les atteignant.",
    quote_13: "La vie est comme faire du vélo. Pour garder votre équilibre, vous devez continuer à avancer.",
    quote_14: "Essayez d'être un arc-en-ciel dans le nuage de quelqu'un d'autre.",
    quote_15: "On ne trouve pas la vie heureuse. On la construit.",
    quote_16: "Le plus gaspillé de tous les jours est celui sans rire.",
    quote_17: "Restez proche de tout ce qui vous rend heureux d'être en vie.",
    quote_18: "Faites de chaque jour votre chef-d'œuvre.",
    quote_19: "Le bonheur se faufile souvent par une porte que vous ne saviez pas avoir laissée ouverte.",
    quote_20: "Le pouvoir de l'imagination nous rend infinis.",
  },
  Kinyarwanda: {
    home: "Ahabanza", play: "Imikino", circles: "Amatsinda", library: "Isomero", settings: "Ibigenerwa", journey: "Urugendo rwanjye", explore: "Gushakisha",
    welcome: "Murakaza neza", activities: "Ibikorwa", current_mood: "Akanyamuneza", mark_complete: "Byarangiye",
    daily_reflection: "Kuzirikana", mindful_moment: "Akanya k'ituze", playlist: "Umuziki",
    search_youtube: "YouTube", select_language: "Ururimi", continue: "Komeza",
    understand_begin: "Gusobanukirwa & Gutangira", last_7_days: "Iminsi 7", welcome_to: "Murakaza muri", how_feeling: "Umeze ute ubu?",
    before_begin: "Mbere yo Gutangira", our_commitment: "Icyo Twiyemeje",
    commitment_text: "Lumora itanga umwanya utekanye ku buzima bwo mu mutwe. Turagufasha ariko ntabwo dusimbura ubuvuzi bw'inzobere mu bitaro.",
    sys_perms: "Uburenganzira bwa Sisitemu", camera: "Kamera", camera_desc: "KUZAMURA IFOTO Y'UMWIRONDORO",
    notifications: "Kumenyeshwa", notify_desc: "KWIYIBUTSA N'UBURINZI",
    location: "Aho uherereye", loc_desc: "IBIKORWA BYEGEREJE",
    Radiant: "Nejejejwe", Peaceful: "Ufite ituze", Tired: "Unaniwe", Anxious: "Uhangayitse", Sad: "Ubabaye", Reflective: "Uri gutekereza",
    top_pick: "Ibyiza kuri wowe", duration: "Igihe", intensity: "Imbaraga",
    preparing: "Turi gutegura ahantu hawe", select_energy: "Hitamo imbaraga zawe ubu", skip: "Simbuka iri taba",
    welcome_plain: "murakaza neza", sign_in: "Injira", sign_up: "Iyandikishe",
    user_placeholder: "Hitamo izina ry'idini", email_placeholder: "Imeli yawe", pass_placeholder: "Ijambo ry'ibanga",
    forgot_pass: "Wibagiwe ijambo ry'ibanga?", begin: "Tugende", ethics_guide: "Iyo winjiye, wemeye amategeko n'amabwiriza yacu.",
    sanctuary: "Ubuturo bwawe bwo Gutuza",
    settings_desc: "Gena uko ubuturo bwawe bumeze", account: "Konti", profile: "Imyirondoro",
    lang_theme: "Ururimi & Isura", app_lang: "Ururimi rwa porogaramu", dark_mode: "Isura y'ijoro",
    safety_privacy: "Umutekano & Ibanga", trusted_guardian: "Umurinzi wizerwa", active_protection: "Uburinzi bukora",
    privacy_controls: "Igenzura ry'ibanga", support_lumora: "Shyigikira Lumora", log_out: "Sohoka",
    circles_desc: "Ahantu hagenewe gusangira ibitekerezo", share_exp: "Sangiza abandi ibyawe", sharing_anon: "Ugiye kwandika utazwi...",
    sharing_as: "Ugiye kwandika nka", post_anon: "Andika utazwi", post_as_user: "Andika nka", share_now: "Sangiza abandi", reply: "Subiza",
    group_1: "Ubufasha ku bahangayitse", group_2: "Intwari za PTSD", group_3: "Kugarura akanyamuneza", group_4: "Itsinda ryo gutuza", group_5: "Agahinda k'urupfu", group_6: "Ubuzima bw'abangavu",
    act_1_title: "Kuhumeka mu gasanduku", act_1_desc: "Uburyo bukoreshwa n'abasirikare mu gutuza umutima.",
    act_2_title: "Gutembera mu bidukikije", act_2_desc: "Bigabanya stress n'umuvuduko w'amaraso.",
    act_3_title: "Kuzirikana umubiri", act_3_desc: "Uburyo bwo kumenya uko umubiri wawe umeze.",
    act_4_title: "Kwandika ibyishimo", act_4_desc: "Gutoza ubwonko kureba ibyiza.",
    book_1_title: "Gushaka icyo ubuzima bivuze", book_1_desc: "Igitabo kivuga ku gushaka intego mu mibabaro.",
    book_2_title: "Umubiri ntiwibagirwa", book_2_desc: "Ivuga ku ngaruka z'ihungabana ku bwonko.",
    quote_1: "Umutima uhengamira ku byo utekereza.",
    quote_2: "Amahoro ava imbere muri wowe.",
    quote_3: "Aka kanya turimo kuzuyemo ibyishimo n'umunezero.",
    quote_4: "Tuza mu mutwe, maze umutima wawe uvuge.",
    quote_5: "Ibisanzwe ntibihubuka, kandi byose birasozwa.",
    reflection_title: "Ituje rya Nimunsi", reflection_text: "Zirikana ikintu kimwe uyu munsi cyaguhaye ituze.",
    playlist_desc: "Umuziki ufungura umutima", min_suffix: "min",
    Medium: "Mucye", High: "Nyinshi", Low: "Nkeya",
    emotional_resonance: "Imiterere y'ibyiyumvo", current_peak: "Igihe cy'intego", status: "Imiterere", rank: "Urwego", days: "Iminsi", balance: "Kubalansa", member: "Umunyamuryango",
    rising: "Iri kuzamuka", falling: "Irimo kumanuka", stable: "Idahinduka",
    setting_2fa: "Umutekano wa 2FA", setting_2fa_desc: "Umutekano Wisumbuye",
    community_other: "Amatsinda & Ibindi",
    MON: "KWA 1", TUE: "KWA 2", WED: "KWA 3", THU: "KWA 4", FRI: "KWA 5", SAT: "KWA 6", SUN: "KWA 7",
    post_1_text: "Uyu munsi nshoboye gusohoka mu nzu.",
    post_2_text: "Nagize umunsi wa mbere utuje.",
    post_3_text: "Agahinda ntikagabanuka.",
    access_resource: "Gukoresha", read_now: "Soma ubu",
    personal_growth: "Igenzura ry'iterambere ryanjye", mindful_streak: "Kudacikwa n'ituze", calm_walker: "Umugenzi utuje",
    recent_milestones: "Ibyo nshoboye kugeraho", peace_guardian: "Umurinzi w'amahoro", peace_guardian_desc: "Kumara icyumweru utuje.",
    clarity_spark: "Kurabagirana kw'ituze", clarity_spark_desc: "Gukora imyitozo 5 mu munsi umwe.",
    daily_insight: "Imbaraga zawe zimeze neza uyu munsi.", rank: "Urwego", days: "Iminsi", balance: "Kubalansa",
    guardian_title: "Umurinzi Wizerwa", guardian_subtitle: "Uburyo bw'Umutekano n'Ubufasha",
    guardian_desc: "Ongeraho umuntu wizera dushobora kwitabaza igihe ukeneye ubufasha bwihariye.",
    guardian_name_placeholder: "Izina ry'Umurinzi", guardian_email_placeholder: "Imeli y'Umurinzi",
    guardian_phone_placeholder: "Telefoni y'Umurinzi", guardian_fill_fields: "Nyamuneka uzuza imyirondoro yose y'umurinzi",
    guardian_saved: "Imyirondoro y'umurinzi yabitswe neza", continue_journey: "Komeza Urugendo", skip_for_now: "Simbuka ubu",
    saving: "Turabika...",
    quote_6: "Ibyishimo ntabwo ari ibintu bikozwe dushonora kugura, biva mu bikorwa byawe bwite.",
    quote_7: "Uburyo bwonyine bwo gukora akazi keza ni ugukunda ibyo ukora.",
    quote_8: "Izere ko ubishoboye maze ube ugeze mu nzira hagati.",
    quote_9: "Kora nkaho ibyo ukora hari icyo bihindura. Kuko koko hari icyo bihindura.",
    quote_10: "Intsinzi ntabwo ari iherezo, kandi gutsindwa ntabwo ari iherezo ry'ubuzima: ubutwari bwo gukomeza nibwo bufite agaciro.",
    quote_11: "Ntukigere unika umutwe. Wamanike hejuru buri gihe. Reba isi mu maso.",
    quote_12: "Icyo ubonye ugeze ku ntego zawe ntabwo ari cyo cy'ingenzi kurusha uwo ubaye we igihe uzigera ho.",
    quote_13: "Ubuzima bumeze nko gutwara igare. Kugira ngo ugumane kuringaniza, ugomba gukomeza kugenda.",
    quote_14: "Gerageza kuba umukororombya mu gicu cy'undi muntu.",
    quote_15: "Ntabwo ubona ubuzima bwishimye. Uburihangira.",
    quote_16: "Umunsi upfuye ubusa kurusha iyindi ni uwo utasezemo.",
    quote_17: "Guma hafi y'ikintu cyose kikwibutsa ko wishimiye kuba uri muzima.",
    quote_18: "Gira umunsi wawe igihangano cy'akataraboneka.",
    quote_19: "Ibyishimo kenshi binyura mu muryango utari uzi ko wasize ufunguye.",
    quote_20: "Imbaraga zo gutekereza ziduhereza amahirwe adafite aho agarukira.",
  },
  Swahili: {
    home: "Nyumbani", play: "Michezo", circles: "Miduara", library: "Maktaba", settings: "Mipangilio", journey: "Safari", explore: "Gundua",
    welcome: "Karibu", activities: "Shughuli", current_mood: "Hali", mark_complete: "Kamilisha",
    daily_reflection: "Tafakari", mindful_moment: "Utulivu", playlist: "Orodha",
    search_youtube: "YouTube", select_language: "Lugha", continue: "Endelea",
    understand_begin: "Elewa & Anza", last_7_days: "Siku 7", welcome_to: "Karibu", how_feeling: "Hali gani?",
    before_begin: "Kabla ya Kuanza", our_commitment: "Ahadi Yetu",
    commitment_text: "Lumora inatoa nafasi salama ya afya ya akili.",
    Radiant: "Mchangamfu", Peaceful: "Mtulivu", Tired: "Mchovu", Anxious: "Mwenye wasiwasi", Sad: "Mhuzunifu", Reflective: "Mwenye kutafakari",
    top_pick: "Chaguo", duration: "Muda", intensity: "Kiwango",
    preparing: "Tunatayarisha nafasi yako", select_energy: "Chagua nishati yako", skip: "Ruka hatua hii",
    welcome_plain: "karibu", sign_in: "Ingia", sign_up: "Jisajili",
    user_placeholder: "Chagua jina la mtumiaji", email_placeholder: "Barua pepe", pass_placeholder: "Nenosiri",
    forgot_pass: "Umesahau Nenosiri?", begin: "Tuanze", ethics_guide: "Unakubali maadili yetu.",
    sanctuary: "Mahali pako pa Utulivu",
    settings_desc: "Binafsisha nafasi yako", account: "Akaunti", profile: "Taarifa za Wasifu",
    lang_theme: "Lugha na Mandhari", app_lang: "Lugha ya Programu", dark_mode: "Modi ya Giza",
    safety_privacy: "Usalama na Faragha", trusted_guardian: "Mlinzi", active_protection: "Ulinzi Amilifu",
    privacy_controls: "Faragha", support_lumora: "Saidia Lumora", log_out: "Ondoka",
    circles_desc: "Nafasi ya Kushiriki", share_exp: "Shiriki uzoefu", sharing_anon: "Kishiriki bila jina...",
    sharing_as: "Kishiriki kama", post_anon: "Tuma bila jina", post_as_user: "Tuma kama", share_now: "Shiriki sasa", reply: "Jibu",
    group_1: "Msaada wa Wasiwasi", group_2: "Mashujaa wa PTSD", group_3: "Kupona Msongo", group_4: "Mduara wa Utulivu", group_5: "Huzuni na Msiba", group_6: "Afya ya Vijana",
    act_1_title: "Kupumua kwa Sanduku", act_1_desc: "Mbinu ya kutuliza mfumo wa neva.",
    act_2_title: "Matembezi ya Asili", act_2_desc: "Inapunguza shinikizo la damu.",
    act_3_title: "Kukagua Mwili", act_3_desc: "Ungana na mwili wako.",
    act_4_title: "Kandika Shukrani", act_4_desc: "Badili akili yako iwe chanya.",
    book_1_title: "Mtafutaji wa Maana ya Maisha", book_1_desc: "Kazi kuhusu kupata maana katika mateso.",
    book_2_title: "Mwili Unatunza Kumbukumbu", book_2_desc: "Inachunguza athari za kiwewe.",
    quote_1: "Nafsi inarangi ya mawazo yake.",
    quote_2: "Amani hutoka ndani.",
    quote_3: "Wakati huu umejaa furaha na heri.",
    quote_4: "Tuliza akili, na nafsi itazungumza.",
    quote_5: "Asili haifanyi haraka, lakini kila kitu kinakamilika.",
    reflection_title: "Utulivu wa Jioni", reflection_text: "Tambua jambo moja lililokupa utulivu.",
    playlist_desc: "Mazingira ya Sauti", min_suffix: "dak",
    Medium: "Kati", High: "Juu", Low: "Chini",
    emotional_resonance: "Mwangwi wa Kihisia", current_peak: "Kiwango cha Juu", status: "Hali", rising: "Inapanda", stable: "Imetulia",
    MON: "Jumatatu", TUE: "Jumanne", WED: "Jumatano", THU: "Alhamisi", FRI: "Ijumaa", SAT: "Jumamosi", SUN: "Jumapili",
    post_1_text: "Leo nimeshiriki kwa mara ya kwanza.",
    post_2_text: "Nimepata siku nzuri.",
    access_resource: "Fungua", read_now: "Soma sasa",
    personal_growth: "Uchambuzi wa Maendeleo", mindful_streak: "Mfululizo wa Utulivu", calm_walker: "Mtembezi Mtulivu",
    recent_milestones: "Mafanikio ya Hivi Karibuni", peace_guardian: "Mlinzi wa Amani", peace_guardian_desc: "Hali ya utulivu kwa wiki nzima.",
    clarity_spark: "Cheche ya Uwazi", clarity_spark_desc: "Kamilisha tafakari 5 kwa siku.",
    daily_insight: "Nishati yako inatiririka vizuri.", rank: "Cheo", days: "Siku", balance: "Mizani"
  },
  Portuguese: {
    home: "Início", play: "Jogos", circles: "Círculos", library: "Biblioteca", settings: "Configurações", journey: "Jornada", explore: "Explorar",
    welcome: "Bem-vindo", activities: "Atividades", current_mood: "Humor", mark_complete: "Concluir",
    daily_reflection: "Reflexão", mindful_moment: "Atenção", playlist: "Playlist",
    search_youtube: "YouTube", select_language: "Idioma", continue: "Continuar",
    understand_begin: "Entender & Começar", last_7_days: "7 dias", welcome_to: "Bem-vindo a", how_feeling: "Como se sente?",
    Radiant: "Radiante", Peaceful: "Tranquilo", Tired: "Cansado", Anxious: "Ansioso", Sad: "Triste", Reflective: "Reflexivo",
    top_pick: "Escolha", duration: "Duração", intensity: "Intensidade",
    preparing: "Preparando seu espaço", select_energy: "Selecione sua energia", skip: "Pular",
    welcome_plain: "bem-vindo", sign_in: "Entrar", sign_up: "Registrar-se",
    user_placeholder: "Nome de usuário", email_placeholder: "E-mail", pass_placeholder: "Senha",
    forgot_pass: "Esqueceu a senha?", begin: "Vamos começar", ethics_guide: "Aceita as diretrizes.",
    sanctuary: "Seu Santuário",
    settings_desc: "Personalize seu espaço", account: "Conta", profile: "Informações",
    lang_theme: "Idioma e Tema", app_lang: "Idioma", dark_mode: "Modo Escuro",
    safety_privacy: "Segurança", trusted_guardian: "Guardião", active_protection: "Proteção Ativa",
    privacy_controls: "Privacidade", support_lumora: "Apoiar", log_out: "Sair",
    circles_desc: "Partilha", share_exp: "Partilhe", sharing_anon: "Como anónimo...",
    sharing_as: "Como", post_anon: "Postar anónimo", post_as_user: "Postar como", share_now: "Partilhar agora", reply: "Responder",
    group_1: "Apoio à Ansiedade", group_2: "Guerreiros PTSD", group_3: "Recuperação", group_4: "Círculo", group_5: "Luto", group_6: "Saúde",
    act_1_title: "Respiração", act_1_desc: "Para regular o sistema nervoso.",
    act_2_title: "Natureza", act_2_desc: "Reduz o cortisol.",
    act_3_title: "Corpo", act_3_desc: "Acalme a mente.",
    act_4_title: "Gratidão", act_4_desc: "Positividade.",
    book_1_title: "Sentido", book_1_desc: "Sobre propósito no sofrimento.",
    book_2_title: "Registo", book_2_desc: "Impacto do trauma.",
    quote_1: "A alma tem a cor dos pensamentos.",
    quote_2: "A paz vem de dentro.",
    quote_3: "O momento presente está cheio de alegria.",
    quote_4: "Acalme a mente e a alma falará.",
    quote_5: "A natureza não se apressa, mas tudo é realizado.",
    reflection_title: "Calma", reflection_text: "O que trouxe paz hoje?",
    playlist_desc: "Sons", min_suffix: "min",
    Medium: "Médio", High: "Alto", Low: "Baixo",
    emotional_resonance: "Ressonância Emocional", current_peak: "Pico Atual", status: "Estado", rising: "Crescente", stable: "Estável",
    MON: "SEG", TUE: "TER", WED: "QUA", THU: "QUI", FRI: "SEX", SAT: "SÁB", SUN: "DOM",
    post_1_text: "Consegui sair de casa.",
    access_resource: "Aceder", read_now: "Ler agora",
    personal_growth: "Análise de Crescimento", mindful_streak: "Série de Atenção", calm_walker: "Caminhante Calmo",
    recent_milestones: "Marcos Recentes", peace_guardian: "Guardião da Paz", peace_guardian_desc: "Humor estável por uma semana.",
    clarity_spark: "Claridade", clarity_spark_desc: "5 meditações num dia.",
    daily_insight: "Sua energia flui bem.", rank: "Nível", days: "Dias", balance: "Equilíbrio"
  },
  Spanish: {
    home: "Inicio", play: "Jugar", circles: "Círculos", library: "Biblioteca", settings: "Ajustes", journey: "Viaje", explore: "Explorar",
    welcome: "Bienvenido", activities: "Actividades", current_mood: "Estado", mark_complete: "Completar",
    daily_reflection: "Reflexión", mindful_moment: "Paz", playlist: "Lista",
    search_youtube: "YouTube", select_language: "Idioma", continue: "Continuar",
    understand_begin: "Entender & Empezar", last_7_days: "7 días", welcome_to: "Bienvenido a", how_feeling: "¿Cómo estás?",
    Radiant: "Radiante", Peaceful: "Tranquilo", Tired: "Cansado", Anxious: "Ansioso", Sad: "Triste", Reflective: "Reflexivo",
    top_pick: "Opción", duration: "Duración", intensity: "Intensidad",
    preparing: "Preparando tu espacio", select_energy: "Selecciona tu energía", skip: "Omitir",
    welcome_plain: "bienvenido", sign_in: "Entrar", sign_up: "Registrarse",
    user_placeholder: "Usuario", email_placeholder: "Correo", pass_placeholder: "Contraseña",
    forgot_pass: "¿Olvidaste?", begin: "Comencemos", ethics_guide: "Pautas éticas.",
    sanctuary: "Santuario Consciente",
    settings_desc: "Personaliza", account: "Cuenta", profile: "Información",
    lang_theme: "Idioma y Tema", app_lang: "Idioma", dark_mode: "Modo Oscuro",
    safety_privacy: "Seguridad", trusted_guardian: "Guardián", active_protection: "Protección",
    privacy_controls: "Privacidad", support_lumora: "Apoyar", log_out: "Cerrar Sesión",
    circles_desc: "Compartir", share_exp: "Comparte", sharing_anon: "Como Anónimo...",
    sharing_as: "Como", post_anon: "Anónimo", post_as_user: "Como", share_now: "Compartir", reply: "Responder",
    group_1: "Ansiedad", group_2: "Guerreros", group_3: "Depresión", group_4: "Círculo", group_5: "Duelo", group_6: "Salud",
    act_1_title: "Respiración", act_1_desc: "Regula el sistema nervioso.",
    act_2_title: "Naturaleza", act_2_desc: "Reduce el cortisol.",
    act_4_title: "Gratitud", act_4_desc: "Positividad.",
    book_1_title: "Sentido", book_1_desc: "Hallar propósito.",
    book_2_title: "Cuerpo", book_2_desc: "Impacto del trauma.",
    quote_1: "El alma tiene color.",
    quote_2: "La paz es interior.",
    quote_3: "El momento presente está lleno de alegría.",
    quote_4: "Aquieta la mente y el alma hablará.",
    quote_5: "La naturaleza no se apresura, pero todo se logra.",
    reflection_title: "Calma", reflection_text: "Qué te trajo paz?",
    playlist_desc: "Paisajes", min_suffix: "min",
    Medium: "Medio", High: "Alto", Low: "Bajo",
    emotional_resonance: "Resonancia Emocional", current_peak: "Pico Actual", status: "Estado", rising: "En aumento", stable: "Estable",
    MON: "LUN", TUE: "MAR", WED: "MIÉ", THU: "JEU", FRI: "VIE", SAT: "SÁB", SUN: "DOM",
    post_1_text: "Sali de casa.",
    access_resource: "Acceder", read_now: "Leer ahora",
    personal_growth: "Analítica de Crecimiento", mindful_streak: "Racha Consciente", calm_walker: "Caminante Tranquilo",
    recent_milestones: "Hitos Recientes", peace_guardian: "Guardián", peace_guardian_desc: "Estado estable una semana.",
    clarity_spark: "Claridad", clarity_spark_desc: "5 meditaciones.",
    daily_insight: "Tu energía fluye.", rank: "Rango", days: "Días", balance: "Equilibrio"
  },
  Russian: {
    home: "Главная", play: "Играть", circles: "Круги", library: "Библиотека", settings: "Настройки", journey: "Путь", explore: "Исследовать",
    welcome: "Добро пожаловать", activities: "Занятия", current_mood: "Настроение", mark_complete: "Завершить",
    daily_reflection: "Раздумья", mindful_moment: "Покой", playlist: "Плейлист",
    search_youtube: "YouTube", select_language: "Язык", continue: "Далее",
    understand_begin: "Понять", last_7_days: "7 дней", welcome_to: "В", how_feeling: "Как вы?",
    Radiant: "Сияющий", Peaceful: "Спокойный", Tired: "Уставший", Anxious: "Тревожный", Sad: "Грустный", Reflective: "Задумчивый",
    top_pick: "Выбор", duration: "Длительность", intensity: "Интенсивность",
    preparing: "Подготовка", select_energy: "Состояние", skip: "Пропустить",
    welcome_plain: "добро пожаловать", sign_in: "Войти", sign_up: "Регистрация",
    user_placeholder: "Имя", email_placeholder: "Почта", pass_placeholder: "Пароль",
    forgot_pass: "Забыли?", begin: "Начнем", ethics_guide: "Этика.",
    sanctuary: "Убежище",
    settings_desc: "Настройте", account: "Аккаунт", profile: "Профиль",
    lang_theme: "Язык", app_lang: "Язык", dark_mode: "Тема",
    safety_privacy: "Безопасность", trusted_guardian: "Опекун", active_protection: "Защита",
    privacy_controls: "Приватность", support_lumora: "Поддержать", log_out: "Выйти",
    circles_desc: "Общение", share_exp: "Поделитесь", sharing_anon: "Анонимно...",
    sharing_as: "От имени", post_anon: "Анонимно", post_as_user: "Как", share_now: "Поделиться", reply: "Ответ",
    group_1: "Тревога", group_2: "Воины", group_3: "Депрессия", group_4: "Круг", group_5: "Горе", group_6: "Здоровье",
    act_1_title: "Дыхание", act_1_desc: "Нервная система.",
    act_2_title: "Природа", act_2_desc: "Кортизол.",
    act_4_title: "Благодарность", act_4_desc: "Позитив.",
    book_1_title: "Смысл", book_1_desc: "Поиск смысла.",
    book_2_title: "Тело", book_2_desc: "Травма.",
    quote_1: "Цвет мыслей.",
    quote_2: "Мир внутри.",
    quote_3: "Настоящий момент полон радости и счастья.",
    quote_4: "Успокойте ум, и душа заговорит.",
    quote_5: "Природа не спешит, но всё успевает.",
    reflection_title: "Покой", reflection_text: "Что принесло покой?",
    playlist_desc: "Звуки", min_suffix: "мин",
    Medium: "Средняя", High: "Высокая", Low: "Низкая",
    emotional_resonance: "Резонанс", current_peak: "Пик", status: "Статус", rising: "Растет", stable: "Стабильно",
    MON: "ПН", TUE: "ВТ", WED: "СР", THU: "ЧТ", FRI: "ПТ", SAT: "СБ", SUN: "ВС",
    post_1_text: "Вышел из дома.",
    access_resource: "Открыть", read_now: "Читать",
    personal_growth: "Рост", mindful_streak: "Серия", calm_walker: "Спокойствие",
    recent_milestones: "Достижения", peace_guardian: "Страж", peace_guardian_desc: "Стабильность неделю.",
    clarity_spark: "Ясность", clarity_spark_desc: "5 медитаций.",
    daily_insight: "Энергия течет.", rank: "Ранг", days: "Дней", balance: "Баланс"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('English');
  const [selectedMood, setSelectedMood] = useState<Mood | null>(null);
  const [userName, setUserName] = useState<string>('Guest');

  const t = (key: string) => {
    return translations[language]?.[key] || translations['English'][key] || key;
  };

  const setMood = (mood: Mood) => setSelectedMood(mood);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, selectedMood, setMood, userName, setUserName, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
